define(function() {
    return {
        "properties": [{
            "name": "minValue",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "sliderSource",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "maxValue",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "pinSource",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "srcLeftBullet",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "srcRightBullet",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "sknRange",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "sknActiveIndex",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "sknInactiveIndex",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "sknSelectedIndex",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "sknBackground",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "skin1",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "intervalDisplay",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "graduations",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "divisions",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "endIndex",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }],
        "apis": ["getSelectedValues"],
        "events": ["onChangeEnd", "onValueChange"]
    }
});